
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/3.31.0/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i"
      binary: "C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i'
        
        Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_db234
        [1/2] C:\\msys64\\mingw64\\bin\\clang.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_db234.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -c C:/msys64/mingw64/share/cmake/Modules/CMakeCCompilerABI.c
        clang version 19.1.4
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: C:/msys64/mingw64/bin
         (in-process)
         "C:/msys64/mingw64/bin/clang.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-sized-deallocation -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i -v -fcoverage-compilation-dir=C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i -resource-dir C:/msys64/mingw64/lib/clang/19 -dependency-file "CMakeFiles\\\\cmTC_db234.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem C:/msys64/mingw64/lib/clang/19/include -internal-isystem C:/msys64/mingw64/x86_64-w64-mingw32/include -internal-isystem C:/msys64/mingw64/x86_64-w64-mingw32/usr/include -internal-isystem C:/msys64/mingw64/include -ferror-limit 19 -femulated-tls -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -fansi-escape-codes -faddrsig -o CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -x c C:/msys64/mingw64/share/cmake/Modules/CMakeCCompilerABI.c\x0d
        clang -cc1 version 19.1.4 based upon LLVM 19.1.4 default target x86_64-w64-windows-gnu\x0d
        ignoring nonexistent directory "C:/msys64/mingw64/x86_64-w64-mingw32/include"\x0d
        ignoring nonexistent directory "C:/msys64/mingw64/x86_64-w64-mingw32/usr/include"\x0d
        #include "..." search starts here:\x0d
        #include <...> search starts here:\x0d
         C:/msys64/mingw64/lib/clang/19/include\x0d
         C:/msys64/mingw64/include\x0d
        End of search list.\x0d
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\msys64\\mingw64\\bin\\clang.exe  -v -Wl,-v CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -o cmTC_db234.exe -Wl,--out-implib,libcmTC_db234.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        clang version 19.1.4
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: C:/msys64/mingw64/bin
         "C:/msys64/mingw64/bin/ld" -m i386pep -Bdynamic -o cmTC_db234.exe C:/msys64/mingw64/lib/crt2.o C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o -LC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0 -LC:/msys64/mingw64/x86_64-w64-mingw32/lib -LC:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib -LC:/msys64/mingw64/lib -v CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_db234.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o\x0d
        GNU ld (GNU Binutils) 2.43.1\x0d
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:182 (message)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/msys64/mingw64/lib/clang/19/include]
          add: [C:/msys64/mingw64/include]
        end of search list found
        collapse include dir [C:/msys64/mingw64/lib/clang/19/include] ==> [C:/msys64/mingw64/lib/clang/19/include]
        collapse include dir [C:/msys64/mingw64/include] ==> [C:/msys64/mingw64/include]
        implicit include dirs: [C:/msys64/mingw64/lib/clang/19/include;C:/msys64/mingw64/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: 'C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i']
        ignore line: []
        ignore line: [Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_db234]
        ignore line: [[1/2] C:\\msys64\\mingw64\\bin\\clang.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_db234.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -c C:/msys64/mingw64/share/cmake/Modules/CMakeCCompilerABI.c]
        ignore line: [clang version 19.1.4]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: C:/msys64/mingw64/bin]
        ignore line: [ (in-process)]
        ignore line: [ "C:/msys64/mingw64/bin/clang.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-sized-deallocation -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i -v -fcoverage-compilation-dir=C:/Users/Okharev/CLionProjects/SkratchRast/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-blbn6i -resource-dir C:/msys64/mingw64/lib/clang/19 -dependency-file "CMakeFiles\\\\cmTC_db234.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem C:/msys64/mingw64/lib/clang/19/include -internal-isystem C:/msys64/mingw64/x86_64-w64-mingw32/include -internal-isystem C:/msys64/mingw64/x86_64-w64-mingw32/usr/include -internal-isystem C:/msys64/mingw64/include -ferror-limit 19 -femulated-tls -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -fansi-escape-codes -faddrsig -o CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -x c C:/msys64/mingw64/share/cmake/Modules/CMakeCCompilerABI.c\x0d]
        ignore line: [clang -cc1 version 19.1.4 based upon LLVM 19.1.4 default target x86_64-w64-windows-gnu\x0d]
        ignore line: [ignoring nonexistent directory "C:/msys64/mingw64/x86_64-w64-mingw32/include"\x0d]
        ignore line: [ignoring nonexistent directory "C:/msys64/mingw64/x86_64-w64-mingw32/usr/include"\x0d]
        ignore line: [#include "..." search starts here:\x0d]
        ignore line: [#include <...> search starts here:\x0d]
        ignore line: [ C:/msys64/mingw64/lib/clang/19/include\x0d]
        ignore line: [ C:/msys64/mingw64/include\x0d]
        ignore line: [End of search list.\x0d]
        ignore line: [[2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\msys64\\mingw64\\bin\\clang.exe  -v -Wl -v CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj -o cmTC_db234.exe -Wl --out-implib libcmTC_db234.dll.a -Wl --major-image-version 0 --minor-image-version 0   && cd ."]
        ignore line: [clang version 19.1.4]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: C:/msys64/mingw64/bin]
        link line: [ "C:/msys64/mingw64/bin/ld" -m i386pep -Bdynamic -o cmTC_db234.exe C:/msys64/mingw64/lib/crt2.o C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o -LC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0 -LC:/msys64/mingw64/x86_64-w64-mingw32/lib -LC:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib -LC:/msys64/mingw64/lib -v CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_db234.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o\x0d]
          arg [C:/msys64/mingw64/bin/ld] ==> ignore
          arg [-m] ==> ignore
          arg [i386pep] ==> ignore
          arg [-Bdynamic] ==> search dynamic
          arg [-o] ==> ignore
          arg [cmTC_db234.exe] ==> ignore
          arg [C:/msys64/mingw64/lib/crt2.o] ==> obj [C:/msys64/mingw64/lib/crt2.o]
          arg [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o] ==> obj [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o]
          arg [-LC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0] ==> dir [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0]
          arg [-LC:/msys64/mingw64/x86_64-w64-mingw32/lib] ==> dir [C:/msys64/mingw64/x86_64-w64-mingw32/lib]
          arg [-LC:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib] ==> dir [C:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib]
          arg [-LC:/msys64/mingw64/lib] ==> dir [C:/msys64/mingw64/lib]
          arg [-v] ==> ignore
          arg [CMakeFiles/cmTC_db234.dir/CMakeCCompilerABI.c.obj] ==> ignore
          arg [--out-implib] ==> ignore
          arg [libcmTC_db234.dll.a] ==> ignore
          arg [--major-image-version] ==> ignore
          arg [0] ==> ignore
          arg [--minor-image-version] ==> ignore
          arg [0] ==> ignore
          arg [-lmingw32] ==> lib [mingw32]
          arg [-lgcc] ==> lib [gcc]
          arg [-lgcc_eh] ==> lib [gcc_eh]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-lpthread] ==> lib [pthread]
          arg [-ladvapi32] ==> lib [advapi32]
          arg [-lshell32] ==> lib [shell32]
          arg [-luser32] ==> lib [user32]
          arg [-lkernel32] ==> lib [kernel32]
          arg [-lmingw32] ==> lib [mingw32]
          arg [-lgcc] ==> lib [gcc]
          arg [-lgcc_eh] ==> lib [gcc_eh]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-lkernel32] ==> lib [kernel32]
          arg [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o] ==> obj [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o]
        linker tool for 'C': C:/msys64/mingw64/bin/ld
        remove lib [gcc_eh]
        remove lib [msvcrt]
        remove lib [gcc_eh]
        remove lib [msvcrt]
        collapse library dir [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0] ==> [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0]
        collapse library dir [C:/msys64/mingw64/x86_64-w64-mingw32/lib] ==> [C:/msys64/mingw64/x86_64-w64-mingw32/lib]
        collapse library dir [C:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib] ==> [C:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib]
        collapse library dir [C:/msys64/mingw64/lib] ==> [C:/msys64/mingw64/lib]
        implicit libs: [mingw32;gcc;moldname;mingwex;pthread;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex;kernel32]
        implicit objs: [C:/msys64/mingw64/lib/crt2.o;C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o;C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o]
        implicit dirs: [C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0;C:/msys64/mingw64/x86_64-w64-mingw32/lib;C:/msys64/mingw64/x86_64-w64-mingw32/mingw/lib;C:/msys64/mingw64/lib]
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "C:/msys64/mingw64/bin/ld" "-v"
      GNU ld (GNU Binutils) 2.43.1
...
